
# spring.datasource.url=jdbc:mysql://localhost:3306/jaamcareer
# spring.datasource.username=root
# spring.datasource.password='root'
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update

spring:
    application:
        name : userservices
    dataSource:
        url: jdbc:mysql://localhost:3306/jaamcareer
        username: root
        password: 'root'
    jpa:
        properties:
            hibernate:
                dialect:${dataSource.dialect}
            connection:
                characterEncoding :  UTF-8
                Charset: UTF-8
                useUnicode: true
        show-sql: true
        hibernate:
            ddl-auto: none

server:
    port:
        8083
