server:
    port: 8081
spring:
    application:
        name:
            API_GATEWAY
    cloud:
        gateway:
            routes:
                - id: userservices
                  uri: http://localhost:8083/
                  predicates:
                     - Path=/user/*
                - id: roleservices
                  uri: http://localhost:8085/
                  predicates:
                     - Path=/role/*
                - id: locationservices
                  uri: http://localhost:8089/
                  predicates:
                     - Path=/location/*
                - id: jobservices
                  uri: http://localhost:8084/
                  predicates:
                     - Path=/job/*
     







                
                # - id: courseModule
                #   uri: lb://course-service
                #   predicates:
                #     - Path=/course/**
        